<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="robots" content="nofollow" />
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<meta name="description" content="<?php echo $result['meta_description']; ?>">
<meta name="author" content="PROFILES RH LLC">
<link rel="icon" href="prhr-logo01-min.ico">
<link rel="canonical" href="<?php echo $result['rel_canonical']; ?>">
<meta name="msvalidate.01" content="BC17EDC8687994A1B27B10E123C9A230" />
<title><?php echo $result['meta_title']; ?></title>
<script defer async src='https://www.google.com/recaptcha/api.js'></script>
<!-- Global site tag (gtag.js) - Google Analytics -->
<!--START Tracking Codes -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-126888354-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());
  gtag('config', 'UA-126888354-1');
</script>
<!--END Tracking Codes -->
<link rel="stylesheet" href="vendor/bootstrap/css/bootstrap.min.css" type="text/css">
<?php if($unite){ ?> 
<script defer type='text/javascript'>
function loadCSS(e, t, n) { "use strict"; var i = window.document.createElement("link"); var o = t || window.document.getElementsByTagName("script")[0]; i.rel = "stylesheet"; i.href = e; i.media = "only x"; o.parentNode.insertBefore(i, o); setTimeout(function () { i.media = n || "all" }) }loadCSS("vendor/unite-gallery/css/unite-gallery.css");
</script>
<?php } ?>
<!--START PAGE CSS -->
<link rel="stylesheet" href="css/<?php echo $result['css']; ?>.min.css" type="text/css">
<!--END PAGE CSS -->
<script defer type='text/javascript'>
function loadCSS(e, t, n) { "use strict"; var i = window.document.createElement("link"); var o = t || window.document.getElementsByTagName("script")[0]; i.rel = "stylesheet"; i.href = e; i.media = "only x"; o.parentNode.insertBefore(i, o); setTimeout(function () { i.media = n || "all" }) }loadCSS("vendor/font-awesome/css/font-awesome.min.css");
</script>
</head>
<!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
<script type="application/ld+json">
{
  "@context" : "http://schema.org",
  "@type" : "LocalBusiness",
  "name" : "PROFILES RH",
  "image" : "http://www.profilesrhf.com/images/prhf-logo-google.jpg",
  "telephone" : "+971 6 5342222",
  "address" : {
    "@type" : "PostalAddress",
    "addressLocality" : "PO Box 656 8 St. Industrial Area 15",
    "addressRegion" : "Sharjah",
    "addressCountry" : "United Arab Emirates"
  }
}
</script>
<script type="application/ld+json">
{
  "@context": "http://schema.org",
  "@type": "Organization",
  "url": "http://www.profilesrhf.com/",
  "logo": "http://www.profilesrhf.com/images/prhf-logo-google.jpg"
  }
}
</script>
<!--Start of Tawk.to Script-->
 <!-- <script type="text/javascript">
var Tawk_API=Tawk_API||{};
Tawk_API.visitor = {
name : 'Name',
email : 'Email'
};

var Tawk_LoadStart=new Date();

(function(){
var s1=document.createElement("script"),s0=document.getElementsByTagName("script")[0];
s1.async=true;
s1.src='js/tawk-modified.min.js';
s1.charset='UTF-8';
s1.setAttribute('crossorigin','*');
s0.parentNode.insertBefore(s1,s0);
})(); 
</script> -->
<!--End of Tawk.to Script-->

